["Leica M6"]
"Exif.Image.Make" = "Leica"
"Exif.Image.Model" = "M6"

["Widelux"]
"Exif.Image.Make" = "Widelux"
"Exif.Image.Model" = "F7"

["Nikon F100"]
"Exif.Image.Make" = "Nikon"
"Exif.Image.Model" = "F100"
